export { default as Layout, type LayoutProps, type LayoutContentProps } from './Layout';
export { default as SEO, type SEOProps } from './SEO';
export { default as Header } from './Header';
export { default as FirstSection } from './FirstSection';
export { default as SecondSection } from './SecondSection';
export { default as ThirdSection } from './ThirdSection';
export { default as FourthSection } from './FourthSection';
export { default as FifthSection } from './FifthSection';
export { default as SixthSection } from './SixthSection';
export { default as SeventhSection } from './SeventhSection';
export { default as EighthSection } from './EighthSection';
export { default as NinthSection } from './NinthSection';
export { default as TenthSection } from './TenthSection';
